#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

git_root=$(git rev-parse --show-toplevel)

fourmolu \
  --mode inplace \
  --ghc-opt -XBangPatterns \
  --ghc-opt -XTypeApplications \
  "${git_root}"/**/*.hs
