#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

if [ -n "${BROWSER}" ]; then
  open="${BROWSER}"
elif command -v xdg-open >/dev/null 2>&1; then
  open="xdg-open"
elif command -v open >/dev/null 2>&1; then
  open="open"
else
  echo "Missing 'open' or 'xdg-open'" >&2
  exit 1
fi

cabal haddock -O0 | tee /dev/stderr | tail -n 1 | xargs "${open}"
