name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        name: Checkout
      - uses: cachix/install-nix-action@v16
        name: Install Nix
      - uses: cachix/cachix-action@v10
        name: Set up Cachix
        with:
          name: evanrelf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
        name: nix-build
